### ISSUE TITLE
Possible regression: _node hello._js: Error: Cannot find module 'streamline/lib/callbacks/runtime'

### ISSUE THREAD

**Issue by ackalker** [Sage/streamlinejs#127]
Installing with `npm install -g ...` from either the npm repository or a clean Git clone, I get this error when trying to run the example._js from the README.md:

```
$ _node hello._js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'streamline/lib/callbacks/runtime'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/miki/proj/streamline/hello._js:1:73)
    at Module._compile (module.js:449:26)
    at Object.streamliners._js [as ._js] (/home/miki/.local/lib/node_modules/streamline/lib/compiler/underscored.js:28:11)
    at Object.run (/home/miki/.local/lib/node_modules/streamline/lib/compiler/underscored.js:91:57)
    at Object.exports.run (/home/miki/.local/lib/node_modules/streamline/lib/compiler/command.js:77:29)
    at Object.<anonymous> (/home/miki/.local/lib/node_modules/streamline/bin/_node:7:14)
```

This appears to be quite similar to issue #95.

Note that I have setup `npm config set prefix $HOME/.local` and added $HOME/.local/bin to my PATH, to enable user-global installs. This works well for all other node packages I've installed user-globally.

**Comment by php5engineer** [comment]
I have the same error. Which directory ```prefix``` should point to? In Webstorm IDE it is project directory by default. But even if I delete it with ```npm config delete prefix``` error persists.

**Comment by bjouhier** [comment]
@php5engineer If prefix points to the project directory and if you have installed streamline globally you should `npm link` streamline to your project directory.

If you upgrade to streamline 1.0 you should install streamline globally and only install streamline-runtime locally in your project.

**Comment by aseemk** [comment]
> If you upgrade to streamline 1.0 you should install streamline globally

Is this really the recommended practice? I've generally found local modules to always be better than global. Even dev tools like Grunt, Gulp, Babel work fine locally (e.g. npm scripts can reference them like normal), to prevent managing dependencies outside/"above" the project.

**Comment by aseemk** [comment]
E.g. analogous with CoffeeScript, which is purely a dev dependency and has no runtime dep:

https://github.com/thingdom/node-neo4j/blob/951008d41798b806f7c29a0d41462d6a015695b8/package.json#L17-L26

**Comment by bjouhier** [comment]
@aseemk 
streamline 1.0 is packaged differently that 0.x versions. There are now 3 packages in NPM:
* `streamline-runtime`. This one should be installed _locally_. It should be in the dependencies of any package that contains transpiled code.
* `babel-plugin-streamline`. This one contains the transpiler. If you use the babel CLI and/or babel API to transpile your streamline source files you do not really need to install streamline. You can just install this package locally.
* `streamline`. This one contains the streamline CLI and API (+ examples, tests and browser runtimes). If you use the streamline CLI (or the _node / _coffee shims) you should probably install it globally. Unlike with 0.x you do not need to have it locally to run your streamlined code, you only need streamline-runtime now. The main advantage of installing streamline globally is that you can run `_node` and `_coffee` from anywhere on your disk.

**Comment by aseemk** [comment]
Thanks for explaining @bjouhier.

One thing you might want to consider then, is to have `streamline` use any locally installed version of `babel-lugin-streamline` (if there is one). That'll prevent version mismatch issues that come with global installs, and this is something that e.g. Grunt and Gulp both support, I believe.

In the meantime, this is the advantage to installing even `streamline` locally. Yes, you don't get `_node` and `_coffee` anywhere, but you can easily add equivalent `scripts` to package.json, and then get e.g. `npm run _node` and `npm run _coffee` (or even better, `npm run repl`).
