### ISSUE TITLE
Futures even for non-Streamline functions?

### ISSUE THREAD

**Issue by aseemk** [Sage/streamlinejs#181]
Now that we have an explicit syntax for saying you want a future (`!_`), any reason Streamline couldn't support returning a future for *any* async function, not just Streamline ones?

Specifically, Streamline's implementation today returns futures from within Streamline function *bodies*... but now that the the compiler can see a `!_` parameter, any reason it couldn't insert a call to create a future for Streamline function *calls* now?

That would be awesome — no more wrappers needed for parallelizing third-party calls.

**Comment by bjouhier** [comment]
@aseemk fixed by #282. That's one of the goodies.

**Comment by aseemk** [comment]
Woot!

**Comment by bjouhier** [comment]
Fixed in 1.0.

**Comment by aseemk** [comment]
Awesome @bjouhier. I'm excited to try this out, but haven't been able to yet.

Quick q in the meantime, if you don't mind: does this mean that non-Streamline functions that are called with a Streamline future will now get a function callback passed to them? (As opposed to `false`.)

Assuming so, awesome! Thanks.

**Comment by bjouhier** [comment]
Yes, that's how it works. The function will receive a callback :smiley:
