### ISSUE TITLE
invalid usage of '_'

### ISSUE THREAD

**Issue by jwalton** [Sage/streamlinejs#183]
This snippet:

    test = (_) ->
        streamlineCall [_]

compiles fine with:

    /node_modules/.bin/_coffee -lp -m -c test._coffee

But this snippet:

    test = (_cb) ->
        streamlineCall [_cb]

compiled with:

    ./node_modules/.bin/_coffee -lp --cb _cb -m -c test._coffee

fails with "Error: invalid usage of '_'" (and doesn't give a line number, which is really annoying btw. ;)

This is a regression - this worked fine in 0.8.0.

**Comment by bjouhier** [comment]
The `--cb` option has been dropped in 1.0. So I'm closing this issue.
