### ISSUE TITLE
Api transform and standalone option

### ISSUE THREAD

**Issue by eurekaa** [Sage/streamlinejs#223]
Hi, great job at first!

I'm trying to transform code programmatically using streamline/lib/callbacks/transform api.
It's all ok for node.js but i'm not able to generate compatibility for browser beacuse the only way to do that is to compile with _node --standalone from shell.

Is there a way to include the 'standalone' option in the transform api?
It would be really appreciated.
Thanks

PS: i'm trying to compile code which has to be executed both on node and on browser, if i compile with the -standalone option it would work on node too?

**Comment by bjouhier** [comment]
In 1.0 you can use streamline together with browserify/babelify. So this problem should be solved. 

So I'm closing the issue for now.
