### ISSUE TITLE
ES6 generators to ES5 compilation

### ISSUE THREAD

**Issue by shirk3y** [Sage/streamlinejs#241]
I wonder if it is possibility to compile ES6's generators down to ES5 like Google Traceur does. This is the only missing feature of Streamline.js I would really need. I personally prefer CoffeeScript over the JS, but Traceur doesn't support it yet. I know that yields works with `--harmony` flag, but I need the code also in the browser. Thoughts?

**Comment by bjouhier** [comment]
No follow-up so I'm closing.
