### ISSUE TITLE
Inconsistent behavior from `streamline/lib/callbacks/transform`

### ISSUE THREAD

**Issue by tellnes** [Sage/streamlinejs#251]
If you are sending in `lines: 'sourcemap'` and a source which does not need transform, then you get the source as string back instead of a `SourceNode`.

I'll understand if this is a wont fix, but it should at least be documented.

**Comment by bjouhier** [comment]
This was an API quirk in 0.x. The new 1.0 API returns `{ code, map }` consistently.
