### ISSUE TITLE
Bug with apply_ inserting an extra callback?

### ISSUE THREAD

**Issue by aseemk** [Sage/streamlinejs#258]
I could very well be doing something wrong here, but I can't figure it out.

What I'm trying to do is the same thing as in #257: write a Streamline wrapper function that can wrap other async functions — which take callbacks as the last parameter.

Since #257 isn't there yet, fellow FiftyThird @chanadian had a nice idea to have the wrapper take the callback *first*, and wrap *it* in a *non-Streamline* function that flips the position of the callback.

Putting that together, here's where I am:

```coffee
wrap = (fn) ->
    # this guy's job is to take the callback first, and put it last:
    bottom = (cb, args...) ->
        console.log 'bottom', arguments
        fn.call @, args..., cb

    # here's the actual dynamic wrapper:
    middle = (_) ->
        console.log 'middle', arguments
        bottom.apply_ _, @, arguments, 0

    # and this guy's job is to take the callback last, and put it first:
    top = (args..., cb) ->
        console.log 'top', arguments
        middle.call @, cb, args...

# here's an example of us wrapping a function:
foo = wrap (str, _) ->
    console.log 'outer', arguments
    setTimeout _, 1
    console.log 'done'

# and here's executing it:
foo 'test', _
```

But when I run it, I get this:

```
top { '0': 'test', '1': { [Function: ___] __streamlined: true } }
middle { '0': { [Function: ___] __streamlined: true }, '1': 'test' }
bottom { '0': { [Function: ___] __streamlined: true },
  '1': { [Function: ___] __streamlined: true },
  '2': 'test' }

/.../node_modules/streamline/lib/callbacks/runtime.js:141
				throw err;
				      ^
Error: invalid callback: string
```

Notice how the `bottom` function got *two* callback arguments!

Looking at [the docs for `fn.apply_`](https://github.com/Sage/streamlinejs/blob/master/lib/compiler/builtins.md#function-functions), I *think* I'm using it right.

Do you see any issue with my code? Or is this indeed a bug in `apply_`?

Thanks!

/cc @ryanwe

**Comment by bjouhier** [comment]
Well, `apply_` _inserts_ the callback at the specified index. This is not a bug; you'd need to slice the arguments to remove the first entry. 

But even this way it won't completely solve your problem because foo will expect the callback as second parameter, not as third, forth, etc., depending on how bottom calls it. See #257.

**Comment by aseemk** [comment]
Oh, whoops! I misunderstood — I thought `args` was supposed to *include* the callback. =)

Thanks for clarifying! That indeed fixes it.

```coffee
wrap = (fn) ->
    actual = (_) ->
        console.log 'wrap actual', arguments
        args = [].slice.call arguments, 1
        console.log '(just args)', args
        fn.apply_ _, @, args
    flipper = (args..., cb) ->
        console.log 'wrap flipper', arguments
        actual.call @, cb, args...

foo = wrap (str, _) ->
    console.log 'foo', arguments
    setTimeout _, 1
    console.log 'done'

foo 'test', _
```

```
wrap flipper { '0': 'test', '1': { [Function: ___] __streamlined: true } }
wrap actual { '0': { [Function: ___] __streamlined: true }, '1': 'test' }
(just args) [ 'test' ]
foo { '0': 'test', '1': { [Function: ___] __streamlined: true } }
done
```

No worries about how the caller calls it: it's expected that if a (wrapped) function is defined with one arg before the callback, the caller must only pass one callback. It's just that we wanted our wrapper function to be generic, to support wrapping functions with different numbers of args.

Sorry for the misunderstanding, and thanks for clarifying!

/cc @ryanwe @chanadian: problem solved. =)
