### ISSUE TITLE
Grunt plugin?  If I wrote one, would you mind linking to it / adopting it?

### ISSUE THREAD

**Issue by cspotcode** [Sage/streamlinejs#260]
Is there an official grunt plugin for compiling streamlined code?

If not, I'll need to write one for my work, so I might as well open-source it.  Would you consider making it official, or at least linking to it from your documentation?

**Comment by bjouhier** [comment]
Hi,

You may want to check with @aponxi. See #138. 

If you publish a plugin to NPM, let me know and I'll mention it in the README (or better, submit the README change as a PR).

I don't want to include optional components into streamline core (not even my own like streamline-flamegraph) but I'm happy to link to external projects.

**Comment by bjouhier** [comment]
There is also a gist from @aikar: https://gist.github.com/aikar/7129221

**Comment by cspotcode** [comment]
Sounds good to me, thank you for the links.

**Comment by aikar** [comment]
Forgot I wrote that... Moved on to gulp now =P

**Comment by bjouhier** [comment]
Thread seems to be dead so I'm closing the issue.
