### ISSUE TITLE
Bower support

### ISSUE THREAD

**Issue by benjiwheeler** [Sage/streamlinejs#266]
Hey, I've been using streamline via bower by just grabbing the entire source, then including transform-all.js in my browser so i can execute code i have run through _coffee on the commandline.

my question is, which are the files from this repo that need to be present if people are using streamline on the client side? eg, transform-all.js... but there are others, right? depending on the situation?

**Comment by benjiwheeler** [comment]
...this is so that i can create a bower.json file and PR it! :)

**Comment by benjiwheeler** [comment]
if it's okay with you, i'm going to register "streamline" with bower so that people can just do 

> bower install streamline

This doesn't give me any special status, you can unregister at any time should you wish, the bower command registry doesn't track who registered what. i don't see any downside except that bower.json should be updated in the future if the set of js files necessary to use streamline on the client side changes.

**Comment by bjouhier** [comment]
I'm ok with it but I'd like the npm and bower versions to be in sync. So if you publish a 0.12.1 you should do it by adding bower.json to the tagged release (without the require fix). Don't publish the current master as a 0.12.1.

I'll publish a 0.12.2 soon and then we can republish on bower.

**Comment by benjiwheeler** [comment]
i'll wait for 0.12.2

**Comment by bjouhier** [comment]
@benjiwheeler I published 1.0.1. I updated the bower.json file but I may have missed something (we don't use bower). If something's broken please tell me and I'll publish a fix quickly.

**Comment by benjiwheeler** [comment]
Thanks! I'll start using it and let you know if there's a problem.
