### ISSUE TITLE
bad to have overridden require() in global namespace?

### ISSUE THREAD

**Issue by benjiwheeler** [Sage/streamlinejs#268]
I'm running into a problem where another library (coffeelint, fyi) makes calls to require() that are being handled by streamline's transform-all.js require() function! :(

Is there any way the require() function in transform-all.js could be renamed, or moved away from the global namespace?

**Comment by bjouhier** [comment]
It should not be too difficult to rename it. I'll take a look later.

**Comment by benjiwheeler** [comment]
Thanks!

**Comment by bjouhier** [comment]
I haven't published to NPM yet. 

I've started to check the code with eslint and I'd like to complete this before publishing. But if you need this quickly I can do an intermediate release.

**Comment by benjiwheeler** [comment]
no, please take your time, i thought it had just been an oversight

-Ben

--------------------
Ben Wheeler
mobile 917.254.1578
latest project: dailydayo.com
personal site: techno-social.com
