### ISSUE TITLE
Promise never resolves

### ISSUE THREAD

**Issue by jwalton** [Sage/streamlinejs#275]
I am looking at some old streamline code we wrote a long time ago which is suddenly doing some... exciting things.  First, we have this coffee-script function which converts an es6 `Promise` into a Streamline future:

```
get = (promise, _) ->
    doit = (done) ->
        promise.then (
            (val) ->
                console.log "*** #{process.pid} Resolving future!"
                done null, val
        ), ((err) -> done err)
    doit _
```

Then we go get a connection from [ampqlib](https://www.npmjs.com/package/amqplib) and assign it to a global variable as a future:

```
connection = null
connectionResolved = false

configure = (server) ->
    connection = get amqp.connect(server)
    connection (err, conn) ->
        return log.error {err} if err
        connectionResolved = true
        console.log "*** #{process.pid} Got connection from future!"
```

And finally, I have this function called "createChannel":

```
exports.createChannel = (name, _) ->
    if !connection? then throw new Error "Not configured"
    console.log "*** #{process.pid} [#{name}] createChannel waiting for connection future - #{connectionResolved}"
    conn = connection(_)
    console.log "*** #{process.pid} [#{name}] createChannel got connection"
    get conn.createChannel(), _
```

In my code, I call `createChannel` twice, and the output I get from the above is:

```
*** 57306 Resolving future!
*** 57306 Got me some connection from future!
*** 57306 notificationService createChannel waiting for connection future - true
*** 57306 scheduler createChannel waiting for connection future - true
*** 57306 scheduler createChannel got connection
```

The "notificationService" call never resolves the future, even though the future was resolved before the call was made.  The future resolves for the "listener" added before in `configure()`, and the "listener" added from the "scheduler" call to `createChannel()`, but never for "notificationService".  Rewriting `createChannel` to be entirely promise based seems to fix the problem:

```
exports.createChannel = (_) ->
    doIt = (done) ->
        if !connectionPromise? then throw new Error "Not configured"
        connectionPromise.then (conn) ->
            conn.createChannel()
        .then (channel) ->
            done null, channel
        .catch (err) ->
            done err
    doIt _
```

**Comment by bjouhier** [comment]
I haven't investigated your code yet but did you consider the built-in support for promises in streamline: https://github.com/Sage/streamlinejs#interoperability-with-promises ? It may help you with promises interop.

**Comment by bjouhier** [comment]
I noticed a few problems in the code. First there is a parenthesing error in the get function. Shouldn't it be:
```coffeescript
get = (promise, _) ->
    doit = (done) ->
        promise.then (
            (val) ->
                console.log "*** #{process.pid} Resolving future!"
                done null, val
           , (err) -> done err)
    doit _
```
Also, the first line of `configure` should be changed to
```coffeescript
    connection = get amqp.connect(server), !_
```
In the early days of streamline you did not need `!_` to get a future, but with recent versions you will get an error if you don't pass anything (unless you use the `--promise` option, in which case you will get a promise in return).

**Comment by jwalton** [comment]
Your bracketing gives an "Unexpected ," in coffee-script 1.9.2.  Mine compiles to:

var get;

get = function(promise, _) {
  var doit;
  doit = function(done) {
    return promise.then(
      (function(val) {
        console.log("*** " + process.pid + " Resolving future!");
        return done(null, val);
      }), 
      (function(err) {
        return done(err);
      })
    );
  };
  return doit(_);
};

(With a little whitespace modification by me for clarity) which looks right to me.

I think the missing `!_` is my fault from trying to edit this so a human could read it.  :P  I'll put the original unedited file [here](https://gist.github.com/jwalton/175e6aaed064014547b2).

I did think about using streamline's built in promise support (I don't think it existed when this was first written - this was also using amqplib ~0.1.1, which didn't even have full A+ promises), but really, this *should* work.  I've kludged it together for now by basically de-streamlining this file and using raw promises.  This was working fine for a long while, but we recently made some changes to how some other things get loaded at startup, which I think caused some timing changes here, and suddenly everything was broken.  :/  It's weird that we create three "listeners" to this promise, and the first one fires, and the last one fires, but the middle one just hangs.

**Comment by bjouhier** [comment]
Right. I'm not familiar enough with CS's parsing rules!

I looked at the code and I don't see why it does not work. What happens if you put a trace before the `promise.then` call inside `get` and traces inside the callback and errback that you pass to `promise.then`?

If only the first trace is called there must be something that prevents the promise to be resolved and I'll need to build a repro without amqplib to investigate why. BTW, which promise library are you using?

**Comment by jwalton** [comment]
I put traces everywhere I could think to, and it seemed like the promise was resolving fine, and as I said, I eventually [re-wrote it with just promises](https://gist.github.com/jwalton/a1377af23d30a440409d) as a workaround.  amqplib uses promises natively, so we're using whatever they're using.  :P  This problem happened on 0.1.1 and latest, though.  I have a feeling this will be hard to reproduce; it was working fine for a very long time, and then suddenly stopped working recently when we changed something completely unrelated (we deferred the initialization of a large data structure until a little later in the startup process.)  So...  Sorry, this is going to be terrible.  :P

**Comment by jwalton** [comment]
If you just close this and pretend it never happened I completely understand.  ;)

**Comment by jwalton** [comment]
Oh, also worth mentioning that the first time I saw this was on v0.10.12, but it seemed to still happen when I upgraded to v0.12.1 (although, now that I think about it, we're using streamline caching, so I might have been running the older cached version...)  I will try to verify this is a problem on v0.12.1 tomorrow.

**Comment by bjouhier** [comment]
Do you mean 0.10.12 or 0.12.0? If the problem appeared in 0.12.0 it could be due to the narcissus -> esprima refactoring. A bug may have crept in.

Can you try with --fibers mode. If the problem shows up in callbacks mode but not in fibers mode then it is definitely a problem with streamline's callbacks transform or runtime.

**Comment by jwalton** [comment]
I'm seeing this in v0.10.x (tried 0.10.9, 0.10.12, 0.10.13.)

And, I'm running into this in a new place:

```
# Run a streamlined function in regular code, logging any error produced.
go = (fn) ->
    future = fn(!_)
    future (err) ->
        if err
            log.error {err}
    return future

class exports.MessageSubscriber
    # Create a new MessageSubscriber.
    #
    # Parameters are the same as for MessagePublisher.
    #
    constructor: (@channelName) ->
        @waitForChannel = go (_) =>
            @channel = common.createChannel _
            # Ensure that the exchange exists.
            get @channel.assertExchange(@channelName, 'topic'), _
            get @channel.prefetch(1), _
            console.log "****************************** Got a channel #{@channelName}!"

    subscribe: (messageType = "#", messageHandler, options={}, done=null) ->
        log.debug "MessageSubscriber: binding to channel #{@channelName}, key #{messageType}"

        subscriberName = "#{@channelName}-subscriber-#{uuid4()}"
        doit = (_) =>
            console.log "Subscribe to #{@channelName}:#{messageType} waiting for channel"
            @waitForChannel _
            console.log "Subscribe to #{@channelName}:#{messageType} got channel"
            # blah blah blah blah

        if done
            doit done
        else
            go doit
```

Here when I call `subscribe` with a callback, I see that the future code completes (the 'Got a channel' console.log gets printed) but the "got channel" console.log sometimes gets printed, and sometimes doesn't.

**Comment by bjouhier** [comment]
I'm closing as 1.0 is using a very different runtime. Please re-open if this is still a problem.
