### ISSUE TITLE
flow annotations

### ISSUE THREAD

**Issue by bjouhier** [Sage/streamlinejs#280]
[Facebook's flow](https://github.com/facebook/flow) sounds interesting. As streamline is a pre-processor, it would be easy to support flow annotations. 

Flow would analyze the untransformed streamline source and the streamline transform would remove them (with [Babel-flow](https://babeljs.io/docs/advanced/transformers/other/flow/)).

Thoughts?

**Comment by bjouhier** [comment]
There is a PR pending in Flow that will make it possible to register `._js` extension so that streamline source files get automatically analyzed by the Flow server: https://github.com/facebook/flow/pull/562

**Comment by gasi** [comment]
:+1: for supporting Flow annotations in Streamline :smile:

**Comment by bjouhier** [comment]
It will be available in 1.0. It's already working in the `reboot` branch. Babel is magic :smile:

**Comment by bjouhier** [comment]
Works with 1.0.2
