### ISSUE TITLE
Package streamline as a babel plugin

### ISSUE THREAD

**Issue by bjouhier** [Sage/streamlinejs#282]

**Comment by aseemk** [comment]
+1!

**Comment by aseemk** [comment]
Lack of (easy) Streamline integration has probably been the single thing holding me back from diving into Babel. =)

**Comment by spollack** [comment]
yes, some way to get streamline plus babel would be excellent!

**Comment by bjouhier** [comment]
Thanks. I'm working on it. The simple diskUsage example works and all our source code compiles but it does not run yet.

I'm expecting lots of benefits:

* ES6 - ES7 features. I've already experimented successfully with classes and flow annotations
* Babel ecosystem - lots of tools (browserify for example) will work with streamline.
* Major code simplification (*) and cleanup, much better APIs, etc.
* Usability improvements: great CLI from babel, very good error messages (I already enjoyed them), etc.

I intend to keep only 2 main modes: callbacks and fibers (exit generators and fast variants). The callbacks mode will use regenerator rather than the original streamline algorithm. I'm actually rewriting from scratch and the new code will be much simpler and much cleaner. See https://github.com/Sage/streamline-plugin and https://github.com/Sage/streamline-runtime.

**Comment by gasi** [comment]
Super excited for this, @bjouhier, as I am experimenting with ES6 + Babel, but would sorely miss Streamline in my repertoire :+1: :100:

**Comment by bjouhier** [comment]
@aseemk @spollack @gasi 
Quick update: this is moving ahead very well. I can now run our application with the new streamline. I still have a few things to do (fix error stacks, test CoffeeScript, packaging, documentation, etc.) but it looks really good. 

The new code is much smaller and much cleaner than the old one and there will be some interesting goodies.

**Comment by aseemk** [comment]
Awesome! Keep up the great work, @bjouhier. Very much looking forward to seeing the result.

**Comment by bjouhier** [comment]
Done!
