### ISSUE TITLE
Function in module.exports without the underscore argument

### ISSUE THREAD

**Issue by php5engineer** [Sage/streamlinejs#284]
Given the FAQ top-level function should have underscore as a last argument. 
Does it mean that anyone whose module will depend on my module will be obliged to use Streamlinejs library? Are there any workarounds for module exports?

``` javascript
function func(foo, bar, _) {
    // ...
}

// will cause this error:
func(foo, bar);

// fixed:
func(foo, bar, _);
```

**Comment by bjouhier** [comment]
You can implement a module with streamline.js and consume it without. For example:

module1._js (streamline.js code)

``` javascript
exports.func = function(foo, bar, _) {
  // ...
}
```

module2.js (vanilla JS code)
``` javascript
require("module1").func("hello", 5, function(err, result) {
  // ...
});
```

You can also mix the two styles in the same file. 

But you cannot call an asynchronous function without a callback.
