### ISSUE TITLE
_node improperly parsing command arguments

### ISSUE THREAD

**Issue by aikar** [Sage/streamlinejs#297]
I'm using _node in a shebang to create scripts, and doing this:

#!/usr/bin/env _node
console.log(process.argv)

However, _node is parsing the command arguments as if it was arguments to the streamline process...

_node should not be looking for streamline flags, as it blocks users from passing their own flags to the app.

So passing myapp -o gives 
[STREAMLINE] obsolete option: -o, use -d or --out-dir instead

But I was intending for MY code to get the -o.

Didn't these commands use to be apart of a sep binary? I was using a really old version of streamline before, and this new everything-in-_node is really removing a core use of _node.

**Comment by bjouhier** [comment]
@aikar That's a bug. I switched to `commander` for command line parsing in 1.0 and I did not anticipate this. I will fix it. Anything that follows the module name should be passed verbatim to the program.
