### ISSUE TITLE
Top level this is replaced by undefined

### ISSUE THREAD

**Issue by bjouhier** [Sage/streamlinejs#303]
See #298

**Comment by bjouhier** [comment]
Problem comes from https://github.com/babel/babel/issues/562

I tried to introduce my own `(function() { ... }).call(this)` IIFE at top level but babel is stubborn and keeps replacing the `this` by `undefined`.

**Comment by bjouhier** [comment]
The solution seems to be to blacklist the `strict` plugin. It can be done via .streamline.json:
```
{
  "runtime": "callbacks",
  "babel": {
    "blacklist": ["strict"]
  }
}
```
I'd rather keep this plugin enabled by default.

**Comment by aseemk** [comment]
Good to know that ES6 modules explicitly define `this` as `undefined` — so my use of top-level `this` isn't wise anymore. Agreed Streamline shouldn't change this by default. Maybe this could be documented, e.g. in the FAQ. Thanks!

**Comment by bjouhier** [comment]
There was nevertheless a problem with the wrapper that streamline is generating if it detects async calls at top level. I'm fixing it in the plugin.
