### ISSUE TITLE
Version issues in streamline

### ISSUE THREAD

**Issue by jwalton** [Sage/streamlinejs#309]
Not 100% sure what part of my project is causing this, but our build broke the other day, complaining about:

    Error: Cannot find module 'streamline-runtime/lib/callbacks/regenerator'

If you try:

```
mkdir temp
cd temp
npm install streamline@1.0.7
```

then you'll notice that ./node_modules/streamline/node_modules/babel-plugin-streamline is v1.0.10, which includes [this bit](https://github.com/Sage/babel-plugin-streamline/blob/v1.0.10/lib/plugin.js#L192), which I assume is causing the problem?

**Comment by jwalton** [comment]
Yeah, this is definitely the problem.  If I `npm install babel-plugin-streamline@1.0.8" before I install streamline, it fixes it.

**Comment by bjouhier** [comment]
The change comes from https://github.com/Sage/streamlinejs/issues/301

I had to change both `babel-plugin-streamline` and `streamline-runtime`. It looks like you are running a newer `babel-plugin-streamline` and an older `streamline-runtime`. Updating the `streamline-runtime` dependency should fix it and work with the latest plugin.

**Comment by bjouhier** [comment]
Looks like `streamline@1.0.7` is botched. I'm getting a different error with `babel-core`.

I encourage you to upgrade to latest streamline (1.0.11). It took me a bit of time to stabilize the new structure (with 3 packages). It should be ok now and I can fix problems moving forwards.

**Comment by jwalton** [comment]
Yeah, I thought you might say that.  :P  Would have been nice to bump the major version for this, though, so it didn't break older versions.
