### ISSUE TITLE
Upgrade to babel 6

### ISSUE THREAD

**Issue by bjouhier** [Sage/streamlinejs#312]
Title says it all. This will be streamline 2.0.

**Comment by jwalton** [comment]
Do you have plans to make it just another babel transform, so you can run if from babel?  That would be slick.

**Comment by bjouhier** [comment]
@jwalton Well, version 1.0 is already a babel transform :smile: 

The transform is now in a separate  [`babel-plugin-streamline`](https://github.com/Sage/babel-plugin-streamline) package. So you do not really need `streamline` any more, unless you use it with CoffeeScript; you can use the plugin directly with `babel`. You can combine the streamline plugin with other babel plugins and with other tools of the babel ecosystem. For example I'm now using `browserify`/`babelify` to deliver streamline to the browser (see `build.js`).

The `streamline` package is still there, though. It provides the `_node` and `_coffee` shims, as well as the streamline REPL, and it ensures compatibility with older versions. But it is only a thin layer around the babel plugin (which itself is rather thin in comparison with the old streamline transforms).

I was planning to short-circuit `streamline` completely in our product and use the plugin directly but the streamline require hooks and cache are more efficient than babel's (speed and memory). So we kept it.

I advise you to wait for streamline 2.0 before investing too much into the plugin. The babel API has changed significantly between babel 5 and babel 6 and I should be able to release 2.0 very soon (the remaining pain point is [a bug in the regenerator transform](https://github.com/babel/babel/pull/3160) which has already been fixed but not yet released.) So it's probably better to wait a few days and start directly with babel 6.

**Comment by bjouhier** [comment]
This is starting to look good and the node.js unit tests pass on 0.10, 0.12 and 4.2 but there is an outstanding issue: the `build.js` script fails when `building lib/browser/transform.js`. This is due to a [known bug in babel / babylon](https://phabricator.babeljs.io/T6930).

So I'm still tagging streamline 2.0 as _beta_ in NPM. Once this is resolved I should be able to make 2.0 _latest_ on NPM.

**Comment by aseemk** [comment]
Very interesting @bjouhier:

> I was planning to short-circuit `streamline` completely in our product and use the plugin directly but the `streamline` require hooks and cache are more efficient than babel's (speed and memory).

Is this still the case with Babel 6? How much? Do you know why? Just curious, thanks. =)

**Comment by bjouhier** [comment]
I haven't re-tested with babel 6 but I have good reasons to think that streamline is still faster. Main reasons:
* babel caches all the compiled files into a single JSON file (`~/.babel.json`). This is ok if you have a small project but the cache file becomes huge in large projects. Loading and parsing this huge file is expensive and it often ends up loading a lot of source that your app does not need (test files for example).
* loading babel itself is very expensive (a few seconds at app startup). The streamline hooks load babel on demand. So app startup is much faster when all the files are already in cache.
