### ISSUE TITLE
Various optimizations

### ISSUE THREAD

**Issue by bjouhier** [Sage/streamlinejs#320]
This issue is just there to track the optimizations that have been implemented in the other packages:

* Sage/babel-plugin-streamline#5
* Sage/babel-plugin-streamline#6
* Sage/streamline-runtime#3
* Sage/streamline-runtime#6

**Comment by aseemk** [comment]
Hey @bjouhier, just out of curiosity, have you considered just keeping all the Streamline sub-modules in this single repo? That would let you manage issues across the modules more easily (and likewise, also let consumers see visibility of issues across the modules more easily), cut releases together, etc.

Babel does this, and it seems to work well for them:

https://github.com/babel/babel/tree/master/packages
https://github.com/babel/babel/blob/master/doc/design/monorepo.md

I don't at all feel strongly here. Just wanted to toss this your way if you hadn't considered it and might find it interesting or helpful. =)

Keep up the great work!

**Comment by aseemk** [comment]
(And to be clear, you could still publish separate `npm` modules. Each folder would still have its own `package.json`, etc. They'd all just live in this single `git` repo.)

**Comment by bjouhier** [comment]
@aseemk I will likely do this at some point. Our internal repo is getting too monolithic and I wanted to experiment with multiple small repos. I went a bit too far (I'm feeling the pain too).

In the short term I will avoid creating issues in the subrepos. I will centralize them in the streamline repo and link to them from the commits / PRs in the other repos. This will improve visibility.

And yes, it needs to be small pieces in NPM.

**Comment by bjouhier** [comment]
I opened a separate issue for the repo discussion. Closing this one.
