### ISSUE TITLE
single repo or single place for issues?

### ISSUE THREAD

**Issue by bjouhier** [Sage/streamlinejs#322]
This is a follow-up of the discussion started by @aseemk in #320. Should we consolidate the various repos (streamline-runtime, babel-plugin-streamline) into a single repo (this one)?

Thinking more about it I would prefer to keep separate repos but disable the GitHub _issues_ features in the other repos. Issues would be centralized here.

I prefer separate repos for code tracking, especially for sensitive pieces like runtime and transform. On the other hand I don't like having issues scattered all over the place; I get lost and I'm probably not the only one.

Note: as @aseemk mentioned, this is just about GitHub, not NPM. We would keep the current package architecture in NPM.

**Comment by aseemk** [comment]
A single place for issues would already be useful to consumers like myself.

You're the primary developer by far, so if your preference for the code is to have multiple repos, there's no reason you shouldn't do that! =)

**Comment by bjouhier** [comment]
Thanks @aseemk. I've disabled issues (and wiki) in the other repos. So I'm closing this.
