### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by bjouhier** [Sage/streamlinejs#332]
Enable streamline inside typescript files.

**Comment by ryanwe** [comment]
Hi @bjouhier,

Is there a recommended way to disable streamline for TypeScript files? I'm working with a project that has both streamlined CoffeeScript files and regular TypeScript files which use `async`/`await` instead of `_`.

I'm running NodeJs 6.3, TypeScript 2.0, and Streamline 2.0.10.

When I run a test that is written in TypeScript (via `ts-node`) and I have `_coffee:streamline/register` in my `mocha.opts` file, I get this error (notice `Cannot find name 'Streamline'`):

(note: I anonymized the error message a bit)
```

project/node_modules/ts-node/src/index.ts:253
          throw new TSError(diagnosticList)
                ^
TSError: ⨯ Unable to compile TypeScript

test/test.ts (13,5): Cannot redeclare block-scoped variable 'uuid'. (2451)
test/test.ts (27,20): Property 'default' does not exist on type '{}'. (2339)
test/test.ts (38,74): Cannot find name 'Streamline'. (2304)
test/test.ts (40,102): Cannot find name 'Streamline'. (2304)
test/test.ts (45,45): Cannot find name 'regeneratorRuntime'. (2304)
test/test.ts (47,16): Cannot find name 'regeneratorRuntime'. (2304)

...

test/test.ts (524,24): Cannot find name 'regeneratorRuntime'. (2304)
test/test.ts (556,52): Cannot find name 'regeneratorRuntime'. (2304)
test/test.ts (559,24): Cannot find name 'regeneratorRuntime'. (2304)
test/test.ts (599,52): Cannot find name 'regeneratorRuntime'. (2304)
test/test.ts (602,24): Cannot find name 'regeneratorRuntime'. (2304)
test/test.ts (631,52): Cannot find name 'regeneratorRuntime'. (2304)
test/test.ts (634,24): Cannot find name 'regeneratorRuntime'. (2304)
test/test.ts (662,52): Cannot find name 'regeneratorRuntime'. (2304)
test/test.ts (665,24): Cannot find name 'regeneratorRuntime'. (2304)
    at getOutput (project/node_modules/ts-node/src/index.ts:253:17)
    at project/node_modules/ts-node/src/index.ts:263:16
    at Object.compile (project/node_modules/ts-node/src/index.ts:398:17)
    at Module.m._compile (project/node_modules/ts-node/src/index.ts:299:46)
    at project/node_modules/streamline/lib/register.js:65:10
    at Object.require.extensions.(anonymous function) [as .ts] (project/node_modules/ts-node/src/index.ts:302:14)
    at Module.load (project/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at project/node_modules/mocha/lib/mocha.js:192:27
    at Array.forEach (native)
    at Mocha.loadFiles (project/node_modules/mocha/lib/mocha.js:189:14)
    at Mocha.run (project/node_modules/mocha/lib/mocha.js:422:31)
    at Object.<anonymous> (project/node_modules/mocha/bin/_mocha:398:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

I want to keep `_coffee:streamline/register` in my `mocha.opts` because I want my tests to reference some `._coffee` files. The only way I've found to make this work is to remove `.ts` from the registered extensions by removing this line. https://github.com/Sage/streamlinejs/blob/master/lib/register.js#L107

But I'd rather not hack streamlinejs if there's a better way. What do you recommend?

Thanks!

**Comment by bjouhier** [comment]
Hi @ryanwe,

I did not anticipate this use case. It is probably cleaner to handle it with an option. 

One way would be to introduce a `strict-extensions` options which would work slightly differently from the current `extensions` option: if `strict-extensions` is present, only the extensions that are present in this list would be registered by streamline.

WDYT?

**Comment by bjouhier** [comment]
Another way would be to allow a special syntax like `"-.ts"` in the existing `extensions` option, to disable extensions that are enabled by default.

**Comment by ryanwe** [comment]
Hi @bjouhier,

Thanks for the quick response! Either approach would work for my use case.

If you're considering adding a new option, maybe `ignore` or `ignore-extensions` would work too.

**Comment by bjouhier** [comment]
Yes that would work too. I just find it easier to specify exactly what you want instead of having to figure out what default + allowed - ignored gives.

**Comment by bjouhier** [comment]
Well, an `ignore` option, aligned on the babel one, would work too, and be more powerful (you could exclude specific directories for example). But it is more work.

Actually, what about `only-extensions`? I like it better than `strict-extensions` because _strict_ could be mis-interpreted as some kind of "strict mode".

**Comment by ryanwe** [comment]
Sounds good to me 👍

**Comment by bjouhier** [comment]
Actually, it is an API-only option, not a command line one. So it will be `onlyExtensions`.

**Comment by bjouhier** [comment]
I'm answering too quickly. `--only-extensions` would also make sense with `-c`.

**Comment by bjouhier** [comment]
@ryanwe I've implemented it and I've run some basic tests (on the command line). I've published it to NPM with the `beta` tag. You can install with `npm install -g streamline@beta`.

Can you try it out and let me know how it goes?

**Comment by ryanwe** [comment]
@bjouhier, 

Wow! Rapid response 😄 

Verifying now...

**Comment by ryanwe** [comment]
It worked locally :tada:, but it ran into a compiler error in CI/Travis.

```
Compiling app...
TypeError: options.onlyExtensions.some is not a function
```

It could be something weird with our CI configuration. I need to run, but I'll take a look later today or tomorrow morning.

**Comment by bjouhier** [comment]
You got lucky. I had some time tonight.

if `option.onlyExtensions` is not null or undefined, it should be an array. I've put a bit of doc in the PR (#335)

**Comment by ryanwe** [comment]
@bjouhier,

Fix confirmed! Thanks again!

**Comment by bjouhier** [comment]
Thanks. I've have removed the `beta` flag and made it `latest` in NPM.
