### ISSUE TITLE
Upgrade typescript support to 2.0

### ISSUE THREAD

**Issue by bjouhier** [Sage/streamlinejs#340]
@tchambard This one is for you 😄 .

**Comment by bjouhier** [comment]
I've published 2.0.13 with the updated dependency.

I need to change the way I'm managing streamline's ambient declarations (streamline.d.ts) so that they can be downloaded with npm. I'll do that when vscode is upgraded to typescript 2.0 (looks like they missed the September drop).

**Comment by tchambard** [comment]
@bjouhier Cool. Thanks a lot 👍
