### ISSUE TITLE
dealing with callers that we can't make asynchronous

### ISSUE THREAD

**Issue by michael-ts** [Sage/streamlinejs#357]
Question one of the FAQ says:

> Asynchronism is contagious. Function foo contains an async call to bar. So foo itself becomes asynchronous and needs an _ in its parameter list.

This would seem to imply that any time I have an async function, every call up the chain must also be async.  But if this is the case, how do I deal with cases where I am being called from another library that I don't have control over?  I'm trying to wrap my head around how I might accomplish this, and am failing.

**Comment by michael-ts** [comment]
Dunno why, but it always seems like when I'm stumped, about five minutes after I create an issue I figure it out... :-D

Anyway, the FAQ example gives:

`function foo() { bar(_); }
`

I can omit the underscore on the foo() function if I do something like this:

function foo() { 
    bar(function(err,ok) {
    }
); 
}

**Comment by bjouhier** [comment]
Yes, you figured it out. 

Any function implemented with streamline is a regular callback-based node.js function. So a library implemented with streamline.js can be consumed like any other node.js library. You should distribute preprocessed code so that people can use your library directly.
